### ISSUE TITLE
Error: attempted to compare a function and a number

### ISSUE THREAD

**Issue by Nick-Mazuk** [LinArcX/telescope-command-palette.nvim#15]
I'm trying to setup the plugin using the configuration outlined in the README. After I call the palette and try and select a category, I get the following error:

```
E5108: Error executing lua ...lette.nvim/lua/telescope/_extensions/command_palette.lua:83: attempt to compare number with function
stack traceback:
        ...lette.nvim/lua/telescope/_extensions/command_palette.lua:83: in function 'entry_maker'
        ...scope.nvim/lua/telescope/finders/async_static_finder.lua:17: in function 'new_table'
        ...lette.nvim/lua/telescope/_extensions/command_palette.lua:76: in function 'commands'
        ...lette.nvim/lua/telescope/_extensions/command_palette.lua:156: in function 'run_replace_or_original'
        ...packer/start/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'key_func'
        ...k/packer/start/telescope.nvim/lua/telescope/mappings.lua:338: in function 'execute_keymap'
        [string ":lua"]:1: in main chunk
```

For further context, it occurs when I see the categories and type "Enter" to select a category.

<img width="1204" alt="Screenshot 2023-02-05 at 9 44 31 AM" src="https://user-images.githubusercontent.com/5659171/216836014-8e5e28db-f4e1-4550-9c0f-e795a489c07a.png">

I don't have any project-specific configuration, and just copy-pasted the [configuration from the README](https://github.com/LinArcX/telescope-command-palette.nvim#setup-and-configuration).

Here's my system information that's returned from `nvim -v`:

```
NVIM v0.8.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Ventura-arm64.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.8.2/share/nvim"

Run :checkhealth for more info
```

**Comment by LinArcX** [comment]
Hello,

Did you install the [telescope](https://github.com/nvim-telescope/telescope.nvim#installation) plugin?

Did you [configure](https://github.com/nvim-telescope/telescope.nvim#telescope-setup-structure) it correctly?

**Comment by adoyle-h** [comment]
The telescope-command-palette.nvim compares `layout_config.width` with a number.

https://github.com/LinArcX/telescope-command-palette.nvim/blob/f7024ea025ed7985d8881d1b535004a1200903f3/lua/telescope/_extensions/command_palette.lua#L80-L83

The problem is the `layout_config.width` of user config may be not a number. It can be a number/table/function.
See [`:h telescope.resolve.resolve_width`](https://github.com/nvim-telescope/telescope.nvim/blob/a3f17d3baf70df58b9d3544ea30abe52a7a832c2/lua/telescope/config/resolve.lua#L215-L230)

**Comment by LinArcX** [comment]
@Nick-Mazuk 

I merged the PR of @adoyle-h, Now you can test. 

Also I'm going to close this issue

Feel free to re-open it, if you still get the same errors.
